# Generated by Django 5.2.11 on 2026-02-27 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesDoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registros_por_pagina', models.PositiveIntegerField(default=100, verbose_name='Número de registros por página')),
                ('ordenar_por', models.CharField(choices=[('-atualizado_em', 'Atualizado em (Z-A)'), ('atualizado_em', 'Atualizado em (A-Z)'), ('-retranca', 'Retranca (Z-A)'), ('retranca', 'Retranca (A-Z)'), ('-status_do_processo__nome', 'Status (Z-A)'), ('status_do_processo__nome', 'Status (A-Z)')], default='-atualizado_em', max_length=50, verbose_name='Ordenar lista por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do usuário',
            },
        ),
    ]
