# Generated by Django 5.2.11 on 2026-02-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_configuracoesdousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoesdousuario',
            name='ordenar_por',
            field=models.CharField(choices=[('-atualizado_em', 'Atualizado em (Z-A)'), ('atualizado_em', 'Atualizado em (A-Z)'), ('-retranca', 'Retranca (Z-A)'), ('retranca', 'Retranca (A-Z)'), ('-status_do_processo__nome', 'Status (Z-A)'), ('status_do_processo__nome', 'Status (A-Z)')], default='-atualizado_em', max_length=50, verbose_name='Ordenar lista de processos por'),
        ),
        migrations.AlterField(
            model_name='configuracoesdousuario',
            name='registros_por_pagina',
            field=models.PositiveIntegerField(default=100, verbose_name='Número de processos por página'),
        ),
    ]
