# Generated by Django 5.2.11 on 2026-03-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_configuracoesdousuario_ordenar_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoesdousuario',
            name='receber_notificacoes_email',
            field=models.BooleanField(default=True, verbose_name='Receber notificações por e-mail'),
        ),
    ]
