# Generated by Django 5.2.11 on 2026-03-03 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('licentia_process', '0008_alter_processlog_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licentia_process.processlog'),
        ),
        migrations.AddField(
            model_name='notification',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licentia_process.process'),
        ),
    ]
