"""
Django settings for licentia_project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_ckeditor_5',

    'core.apps.CoreConfig',
    'licentia_resources.apps.LicentiaResourcesConfig',
    'licentia_process.apps.LicentiaProcessConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'licentia_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'licentia_resources.context_processors.recursos_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'licentia_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Exibe o e-mail de recuperação no terminal do VS Code/Console
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

CKEDITOR_5_CONFIGS = {
    'default': {
        'plugins': [
            'SourceEditing', 'HtmlEmbed', 'GeneralHtmlSupport',
            'Essentials', 'Paragraph', 'Bold', 'Italic', 'Heading', 'List',
            'Style', 'RemoveFormat',
        ],
        'language': 'pt-br',
        'toolbar': [
            'style', 'removeFormat', '|', 
            'htmlEmbed', 'sourceEditing', '|', 
            'bold', 'italic', '|', 'bulletedList', 'numberedList', '|', 
            'undo', 'redo'
        ],
        'style': {
            'definitions': [
                {'name': 'c3idioma', 'element': 'span', 'classes': ['c3idioma']},
                {'name': 'c3idiomabold', 'element': 'span', 'classes': ['c3idiomabold']},
                {'name': 'c3idiomaitalico', 'element': 'span', 'classes': ['c3idiomaitalico']},
                {'name': 'c3idiomabolditalico', 'element': 'span', 'classes': ['c3idiomabolditalico']},
                {'name': 'equacao_latex', 'element': 'span', 'classes': ['latex']},
            ]
        },
        'htmlEmbed': {
            'showPreviews': True,
        },
        'htmlSupport': {
            'allow': [
                {
                    'name': '\w+',
                    'attributes': True,
                    'classes': True,
                    'styles': True
                }
            ]
        },
        'extends': {
            'language': 'pt-br',
        },
        'editorConfig': {
            'browserSpellcheck': True,
        },
    }
}

X_FRAME_OPTIONS = 'SAMEORIGIN'