# Generated by Django 5.2.11 on 2026-02-25 15:45

import django.db.models.deletion
import django_ckeditor_5.fields
import licentia_process.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_process', '0001_initial'),
        ('licentia_resources', '0003_rename_statusdoprocessopagamento_centrodecusto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocess',
            name='capitulo_secao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capítulo ou seção'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='credito_obrigatorio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Crédito obrigatório'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='observacao_autrec',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Observação AutRev'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='observacao_editorial',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Observação editorial'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='status_do_orcamento',
            field=models.ForeignKey(blank=True, db_constraint=False, default=licentia_process.models.get_default_status_orcamento, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='licentia_resources.statusdoorcamento', verbose_name='Status do orçamento'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='status_do_orcamento_aprovacao',
            field=models.ForeignKey(blank=True, db_constraint=False, default=licentia_process.models.get_default_status_orcamento_aprovacao, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='licentia_resources.statusdoorcamentoaprovacao', verbose_name='Status do orçamento aprovação'),
        ),
        migrations.AlterField(
            model_name='process',
            name='capitulo_secao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capítulo ou seção'),
        ),
        migrations.AlterField(
            model_name='process',
            name='credito_obrigatorio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Crédito obrigatório'),
        ),
        migrations.AlterField(
            model_name='process',
            name='observacao_autrec',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Observação AutRev'),
        ),
        migrations.AlterField(
            model_name='process',
            name='observacao_editorial',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Observação editorial'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status_do_orcamento',
            field=models.ForeignKey(blank=True, default=licentia_process.models.get_default_status_orcamento, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_status_orcamento', to='licentia_resources.statusdoorcamento', verbose_name='Status do orçamento'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status_do_orcamento_aprovacao',
            field=models.ForeignKey(blank=True, default=licentia_process.models.get_default_status_orcamento_aprovacao, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_status_orcamento_aprovacao', to='licentia_resources.statusdoorcamentoaprovacao', verbose_name='Status do orçamento aprovação'),
        ),
    ]
