# Generated by Django 5.2.11 on 2026-02-25 23:34

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_process', '0002_alter_historicalprocess_capitulo_secao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocess',
            name='observacao_autrec',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Observação AutRec'),
        ),
        migrations.AlterField(
            model_name='process',
            name='observacao_autrec',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Observação AutRec'),
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Relato da atividade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='licentia_process.process')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do processo',
                'verbose_name_plural': 'Logs do processo',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
