# Generated by Django 5.2.11 on 2026-02-26 01:29

import django.db.models.deletion
import licentia_process.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_process', '0003_alter_historicalprocess_observacao_autrec_and_more'),
        ('licentia_resources', '0003_rename_statusdoprocessopagamento_centrodecusto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocess',
            name='status_do_processo',
            field=models.ForeignKey(blank=True, db_constraint=False, default=licentia_process.models.get_default_status_processo, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='licentia_resources.statusdoprocesso', verbose_name='Status do processo'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status_do_processo',
            field=models.ForeignKey(blank=True, default=licentia_process.models.get_default_status_processo, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_status_do_processo', to='licentia_resources.statusdoprocesso', verbose_name='Status do processo'),
        ),
    ]
