# Generated by Django 5.2.11 on 2026-02-27 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_process', '0004_alter_historicalprocess_status_do_processo_and_more'),
        ('licentia_resources', '0003_rename_statusdoprocessopagamento_centrodecusto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_componente', to='licentia_resources.componente', verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='process',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_projeto', to='licentia_resources.projeto', verbose_name='Projeto'),
        ),
    ]
