# Generated by Django 5.2.11 on 2026-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_process', '0005_alter_process_componente_alter_process_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocess',
            name='titulo_descricao',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Título ou descrição'),
        ),
        migrations.AlterField(
            model_name='process',
            name='titulo_descricao',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Título ou descrição'),
        ),
    ]
