# Generated by Django 5.2.11 on 2026-03-03 11:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_process', '0006_alter_historicalprocess_titulo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='texto',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Relato da atividade'),
        ),
    ]
