# Generated by Django 5.2.11 on 2026-03-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_process', '0007_alter_processlog_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='texto',
            field=models.TextField(verbose_name='Relato da atividade'),
        ),
    ]
