# Generated by Django 5.2.11 on 2026-02-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='statusdofreelapagamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='statusdoprocesso',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='statusdoprocessopagamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
