# Generated by Django 5.2.11 on 2026-02-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_resources', '0003_rename_statusdoprocessopagamento_centrodecusto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdoorcamento',
            name='cor',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('yellow', 'Amarelo'), ('purple', 'Roxo'), ('orange', 'Laranja'), ('teal', 'Verde-Água')], default='blue', verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='statusdoorcamentoaprovacao',
            name='cor',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('yellow', 'Amarelo'), ('purple', 'Roxo'), ('orange', 'Laranja'), ('teal', 'Verde-Água')], default='blue', verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='statusdoprocesso',
            name='cor',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('yellow', 'Amarelo'), ('purple', 'Roxo'), ('orange', 'Laranja'), ('teal', 'Verde-Água')], default='blue', verbose_name='Cor'),
        ),
    ]
