# Generated by Django 5.2.11 on 2026-02-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_resources', '0004_statusdoorcamento_cor_statusdoorcamentoaprovacao_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdoorcamento',
            name='cor',
            field=models.CharField(choices=[('blue', 'Azul'), ('azure', 'Azul Marinho'), ('indigo', 'Indigo'), ('purple', 'Roxo'), ('pink', 'Rosa'), ('red', 'Vermelho'), ('orange', 'Laranja'), ('yellow', 'Amarelo'), ('lime', 'Lima'), ('green', 'Verde'), ('teal', 'Verde-Água'), ('cyan', 'Ciano'), ('gray', 'Cinza'), ('dark', 'Preto/Escuro')], default='blue', verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='statusdoorcamentoaprovacao',
            name='cor',
            field=models.CharField(choices=[('blue', 'Azul'), ('azure', 'Azul Marinho'), ('indigo', 'Indigo'), ('purple', 'Roxo'), ('pink', 'Rosa'), ('red', 'Vermelho'), ('orange', 'Laranja'), ('yellow', 'Amarelo'), ('lime', 'Lima'), ('green', 'Verde'), ('teal', 'Verde-Água'), ('cyan', 'Ciano'), ('gray', 'Cinza'), ('dark', 'Preto/Escuro')], default='blue', verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='statusdoprocesso',
            name='cor',
            field=models.CharField(choices=[('blue', 'Azul'), ('azure', 'Azul Marinho'), ('indigo', 'Indigo'), ('purple', 'Roxo'), ('pink', 'Rosa'), ('red', 'Vermelho'), ('orange', 'Laranja'), ('yellow', 'Amarelo'), ('lime', 'Lima'), ('green', 'Verde'), ('teal', 'Verde-Água'), ('cyan', 'Ciano'), ('gray', 'Cinza'), ('dark', 'Preto/Escuro')], default='blue', verbose_name='Cor'),
        ),
    ]
