# Generated by Django 5.2.11 on 2026-03-02 17:24

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_resources', '0005_alter_statusdoorcamento_cor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('assunto', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Assunto do e-mail')),
                ('mensagem', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Mensagem do e-mail')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador por')),
            ],
            options={
                'verbose_name': 'Template de e-mail',
                'verbose_name_plural': 'Templates de e-mail',
                'ordering': ['nome'],
            },
        ),
    ]
