# Generated by Django 5.2.11 on 2026-03-03 11:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licentia_resources', '0006_templatedeemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedeemail',
            name='assunto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Acesse <a href="https://www.google.com.br" target="_blank" class="text-primary fw-bold">https://www.google.com.br</a> para ajuda.', null=True, verbose_name='Assunto do e-mail'),
        ),
        migrations.AlterField(
            model_name='templatedeemail',
            name='mensagem',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Acesse <a href="https://www.google.com.br" target="_blank" class="text-primary fw-bold">https://www.google.com.br</a> para ajuda.', null=True, verbose_name='Mensagem do e-mail'),
        ),
    ]
